FROM openjdk
ADD microservicio_pedidos.jar servicios/pedidos.jar
ENV hostconfig=192.168.1.69
ENV hostdb=192.168.1.69
ENV hostreal=192.168.1.69
ENV hosteureka=192.168.1.69
ENV portdb=3306
ENTRYPOINT java -jar servicios/pedidos.jar