spring:
  application:
    name: servidor-gateway   
  cloud: 
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: servProductos 
        uri: lb://servicio-productos
        predicates:
          - Path=/sproductos/** 
        filters:
          - RewritePath=/sproductos/*, /          
      - id: servPedidos
        uri: lb://servicio-pedidos
        predicates:
          - Path=/spedidos/**
        filters:
          - RewritePath=/spedidos/*, /      
server:
  port: 10000
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka